### ISSUE TITLE
기타 기능 - 댓글 삭제

### ISSUE THREAD

**Issue by sehyeogg365** [sehyeogi360/ChoongMoTour#27]

**Comment by sehyeogi360** [comment]
Parameter index out of range (1 > number of parameters, which is 0).

**Comment by sehyeogi360** [comment]
그위에 쿼리문에 ` 하나가 안찍혀서 생긴오류였던것

	SELECT
  		`id`
  		, `userId
  		, `roomId`
  		, `content`
  		, `imagPath`
  		, `starpoint`
  	FROM
  		`comment`
  	WHERE
  		`id` = #{id};

**Comment by sehyeogi360** [comment]
컬러명에 오타있다고 또 오류뜸

`imagPath` 이렇게

**Comment by sehyeogi360** [comment]
댓글 삭제 자체는 성공했다.

그런데 여기서 로그인한 유저가 쓴 댓글만 x자 뜨게 그것도 해보기

**Comment by sehyeogi360** [comment]
댓글 삭제 분명히 어젠 잘됐는데 또 왜그런가

아난티코브에선 실패가 떠서 한번 새로고침하니 삭제가 되고

웨스틴조선서는 아예 에러가 뜬다.

**Comment by sehyeogi360** [comment]
웨스틴에서 사진없는거를 삭제해도 똑같다.

Cannot invoke "com.marondal.choongmotour.lodging.model.Comment.getImagePath()" because "comment" is null

commentBO에서 문제가 있고,

comment 객체가 null이란건데 왜그럴까? 

혹시 댓글리스트도 마찬가지인가? 이런거 떔에?

**Comment by sehyeogi360** [comment]
강원호텔도 삭제는 된다 근데 웨스틴 조선은 안된다??

**Comment by sehyeogi360** [comment]
디버깅모드 결과 잘들어오고 있다 모든값들이

**Comment by sehyeogi360** [comment]
아예 그냥 웨스틴 조선을 삭제해버렸다. 다른 호텔은 잘되는데 이것만 이러는게 꺼림찍하다.

**Comment by sehyeogi360** [comment]
기타 오류긴한데 웨스틴 조선 삭제후 예약목록이 안들어가지는 오류가 왜 떴냐면.

웨스틴조선을 삭제했는데 예약목록서는 남아있어서 그랬나보다.

그래서 아예 테이블 truncate 하니까 들어가진다 다행이네

**Comment by sehyeogi360** [comment]
현재 웨스틴 조선이랑, WE 제주 호텔만 이런 500에러 뜨는데

이런 오류다. 근데 혹시나 해서 웨스틴 조선 삭제후 다른 사진 올리고 부산 웨스틴 조선이라고 하니까 잘된다? 혹시 사진문제인가 잘모르겠다 계속 테스트 해보기 
java.lang.NullPointerException: Cannot invoke "com.marondal.choongmotour.lodging.model.Comment.getImagePath()" because "comment" is null
	at com.marondal.choongmotour.lodging.comment.bo.CommentBO.deleteComment(CommentBO.java:95) ~[main/:na]
	at com.marondal.choongmotour.lodging.LodgingRestController.commentDelete(LodgingRestController.java:172) ~[main/:na]

**Comment by sehyeogi360** [comment]
정말 혹시나해서 다른거 올리고 웨스틴 조선 삭제후 다시 올려보니 또 댓글삭제가 된다 왜그럴까?

근데 이건 진짜 나중가서 연구해볼 문제고, 지금은 이렇게 해보자

**Comment by sehyeogi360** [comment]
현재 WE호텔 삭제후 다시 해봤는데 같은오류가 뜬다 혹시나해서 새로 만든 웨스틴 조선에

숙소 프사랑 같은 사진을 댓글에 올려서 했는데 삭제 잘만된다?

그럼 도대체 뭐가 원인일까?
